const db=require('../config/database');const AppError=require('../utils/AppError');
const priorities=['normal','important','urgent'],audiences=['all','managers','employees'];
const clean=v=>typeof v==='string'?v.trim():v;
const profile=userId=>db.prepare('SELECT e.id,u.role FROM employees e JOIN users u ON u.id=e.user_id WHERE e.user_id=?').get(userId);
const row=id=>db.prepare(`SELECT a.*,e.first_name||' '||e.last_name creator_name,e.employee_id creator_code FROM announcements a JOIN employees e ON e.id=a.created_by WHERE a.id=?`).get(id);
function canManage(p){return p&&(p.role==='admin'||p.role==='manager');}
function list(req,res){const p=profile(req.user.id);const rows=db.prepare(`SELECT a.*,e.first_name||' '||e.last_name creator_name,e.employee_id creator_code FROM announcements a JOIN employees e ON e.id=a.created_by ORDER BY CASE a.priority WHEN 'urgent' THEN 0 WHEN 'important' THEN 1 ELSE 2 END,a.created_at DESC`).all();res.json({success:true,data:rows});}
function mine(req,res){const p=profile(req.user.id);if(!p)throw new AppError('Employee profile not found.',404);const rows=db.prepare(`SELECT a.*,e.first_name||' '||e.last_name creator_name,e.employee_id creator_code FROM announcements a JOIN employees e ON e.id=a.created_by WHERE a.target_audience='all' OR a.target_audience=? ORDER BY CASE a.priority WHEN 'urgent' THEN 0 WHEN 'important' THEN 1 ELSE 2 END,a.created_at DESC`).all(p.role);res.json({success:true,data:rows});}
function detail(req,res){const a=row(req.params.id);if(!a)throw new AppError('Announcement not found.',404);res.json({success:true,data:a});}
function validate(b){if(!clean(b.title))throw new AppError('Title is required.',400);if(!clean(b.message))throw new AppError('Message is required.',400);if(!priorities.includes(b.priority))throw new AppError('Invalid priority.',400);if(!audiences.includes(b.target_audience))throw new AppError('Invalid target audience.',400);}
function create(req,res){const p=profile(req.user.id);if(!canManage(p))throw new AppError('You are not authorized to create announcements.',403);validate(req.body);const b=req.body,r=db.prepare('INSERT INTO announcements(title,message,priority,target_audience,created_by) VALUES(?,?,?,?,?)').run(clean(b.title),clean(b.message),b.priority,b.target_audience,p.id);res.status(201).json({success:true,data:row(r.lastInsertRowid)});}
function update(req,res){const p=profile(req.user.id);if(!canManage(p))throw new AppError('You are not authorized to edit announcements.',403);const old=row(req.params.id);if(!old)throw new AppError('Announcement not found.',404);validate(req.body);const b=req.body;db.prepare('UPDATE announcements SET title=?,message=?,priority=?,target_audience=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(clean(b.title),clean(b.message),b.priority,b.target_audience,old.id);res.json({success:true,data:row(old.id)});}
function remove(req,res){const p=profile(req.user.id);if(!canManage(p))throw new AppError('You are not authorized to delete announcements.',403);const old=row(req.params.id);if(!old)throw new AppError('Announcement not found.',404);db.prepare('DELETE FROM announcements WHERE id=?').run(old.id);res.json({success:true,message:'Announcement deleted.'});}
module.exports={list,mine,detail,create,update,remove};