const bcrypt = require('bcrypt');
const db = require('../config/database');
const AppError = require('../utils/AppError');
const { generateTemporaryPassword } = require('../utils/temporaryPassword');

const clean = (v) => typeof v === 'string' ? v.trim() : v;
const departmentById = (id) => db.prepare('SELECT id, name, description, created_at, updated_at FROM departments WHERE id = ?').get(id);
const employeeById = (id) => db.prepare(`SELECT e.*, u.email, u.role, u.is_active, d.name department_name, m.first_name || ' ' || m.last_name manager_name FROM employees e JOIN users u ON u.id=e.user_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN employees m ON m.id=e.manager_id WHERE e.id=?`).get(id);
function departments(req,res){ res.json({success:true,data:db.prepare('SELECT d.*, COUNT(e.id) employee_count FROM departments d LEFT JOIN employees e ON e.department_id=d.id GROUP BY d.id ORDER BY d.name').all()}); }
function department(req,res){ const row=departmentById(req.params.id); if(!row) throw new AppError('Department not found.',404); res.json({success:true,data:{...row,employee_count:db.prepare('SELECT COUNT(*) count FROM employees WHERE department_id=?').get(req.params.id).count}}); }
function createDepartment(req,res){ const name=clean(req.body?.name); if(!name) throw new AppError('Department name is required.',400); try { const result=db.prepare('INSERT INTO departments(name,description) VALUES(?,?)').run(name,clean(req.body.description)||null); res.status(201).json({success:true,data:departmentById(result.lastInsertRowid)}); } catch(e){ if(e.code?.includes('CONSTRAINT')) throw new AppError('Department name must be unique.',409); throw e; } }
function updateDepartment(req,res){ const name=clean(req.body?.name); if(!name) throw new AppError('Department name is required.',400); if(!departmentById(req.params.id)) throw new AppError('Department not found.',404); try { db.prepare('UPDATE departments SET name=?,description=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(name,clean(req.body.description)||null,req.params.id); res.json({success:true,data:departmentById(req.params.id)}); } catch(e){ if(e.code?.includes('CONSTRAINT')) throw new AppError('Department name must be unique.',409); throw e; } }
function deleteDepartment(req,res){ if(!departmentById(req.params.id)) throw new AppError('Department not found.',404); const count=db.prepare('SELECT COUNT(*) count FROM employees WHERE department_id=?').get(req.params.id).count; if(count) throw new AppError('This department cannot be deleted because employees are assigned to it.',409); db.prepare('DELETE FROM departments WHERE id=?').run(req.params.id); res.json({success:true,message:'Department deleted.'}); }
function employees(req,res){ const {search,department_id,status}=req.query; const where=[]; const params=[]; if(search){where.push('(e.first_name LIKE ? OR e.last_name LIKE ? OR e.employee_id LIKE ? OR u.email LIKE ?)'); const s=`%${search}%`;params.push(s,s,s,s);} if(department_id){where.push('e.department_id=?');params.push(department_id);} if(status==='active'||status==='inactive'){where.push('u.is_active=?');params.push(status==='active'?1:0);} const sql=`SELECT e.id,e.employee_id,e.first_name,e.last_name,e.job_position,e.joining_date,e.profile_picture,u.email,u.role,u.is_active,d.name department_name,m.first_name || ' ' || m.last_name manager_name FROM employees e JOIN users u ON u.id=e.user_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN employees m ON m.id=e.manager_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY e.first_name,e.last_name`; res.json({success:true,data:db.prepare(sql).all(...params)}); }
function employee(req,res){ const row=employeeById(req.params.id); if(!row) throw new AppError('Employee not found.',404); res.json({success:true,data:row}); }
function validateEmployee(body,id){ const required=['first_name','last_name','employee_id','email','job_position','joining_date']; for(const field of required) if(!clean(body[field])) throw new AppError(`${field.replace('_',' ')} is required.`,400); if(body.department_id && !departmentById(body.department_id)) throw new AppError('Invalid department.',400); if(body.manager_id){if(Number(body.manager_id)===Number(id)) throw new AppError('An employee cannot be their own manager.',400); const m=employeeById(body.manager_id); if(!m||m.role!=='manager') throw new AppError('Invalid manager.',400);} }
function createEmployee(req,res){ const b=req.body||{}; validateEmployee(b); if(!clean(b.password)) throw new AppError('Temporary password is required.',400); if(!['manager','employee'].includes(b.role||'employee')) throw new AppError('Role must be manager or employee.',400); db.exec('BEGIN'); try { const u=db.prepare('INSERT INTO users(email,password,role) VALUES(?,?,?)').run(clean(b.email).toLowerCase(),bcrypt.hashSync(b.password,12),b.role); const e=db.prepare('INSERT INTO employees(user_id,employee_id,first_name,last_name,department_id,manager_id,job_position,joining_date,profile_picture) VALUES(?,?,?,?,?,?,?,?,?)').run(u.lastInsertRowid,clean(b.employee_id),clean(b.first_name),clean(b.last_name),b.department_id||null,b.manager_id||null,clean(b.job_position),b.joining_date,b.profile_picture||null); db.exec('COMMIT'); res.status(201).json({success:true,data:employeeById(e.lastInsertRowid)}); } catch(e){db.exec('ROLLBACK'); if(e.code?.includes('CONSTRAINT')) throw new AppError('Email or employee ID already exists.',409); throw e;} }
function updateEmployee(req,res){ const old=employeeById(req.params.id); if(!old) throw new AppError('Employee not found.',404); const b={...old,...req.body}; validateEmployee(b,req.params.id); try { db.prepare('UPDATE employees SET employee_id=?,first_name=?,last_name=?,department_id=?,manager_id=?,job_position=?,joining_date=?,profile_picture=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(clean(b.employee_id),clean(b.first_name),clean(b.last_name),b.department_id||null,b.manager_id||null,clean(b.job_position),b.joining_date,b.profile_picture||null,req.params.id); res.json({success:true,data:employeeById(req.params.id)}); } catch(e){if(e.code?.includes('CONSTRAINT')) throw new AppError('Employee ID already exists.',409); throw e;} }
function status(req,res){ const row=employeeById(req.params.id); if(!row) throw new AppError('Employee not found.',404); if(Number(row.user_id)===Number(req.user.id)) throw new AppError('You cannot deactivate your own account.',400); if(typeof req.body?.is_active!=='boolean') throw new AppError('is_active must be boolean.',400); db.prepare('UPDATE users SET is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(req.body.is_active?1:0,row.user_id); res.json({success:true,message:`Employee ${req.body.is_active?'activated':'deactivated'}.`}); }
function resetPassword(req,res){ const row=employeeById(req.params.id); if(!row) throw new AppError('Employee not found.',404); if(Number(row.user_id)===Number(req.user.id)) throw new AppError('You cannot reset your own password from employee management. Use the account password change feature.',400); const temporaryPassword=generateTemporaryPassword(); db.prepare('UPDATE users SET password=?,must_change_password=1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(bcrypt.hashSync(temporaryPassword,12),row.user_id); res.json({success:true,message:'Password reset successfully.',employee:{id:row.id,employee_id:row.employee_id,name:`${row.first_name} ${row.last_name}`,email:row.email},temporaryPassword}); }
function managers(req,res){res.json({success:true,data:db.prepare("SELECT e.id,e.first_name,e.last_name,e.employee_id FROM employees e JOIN users u ON u.id=e.user_id WHERE u.role='manager' AND u.is_active=1 ORDER BY e.first_name").all()});}
function adminStats(req,res){ const q=(sql)=>db.prepare(sql).get().count; res.json({success:true,data:{totalEmployees:q('SELECT COUNT(*) count FROM employees'),activeEmployees:q('SELECT COUNT(*) count FROM employees e JOIN users u ON u.id=e.user_id WHERE u.is_active=1'),inactiveEmployees:q('SELECT COUNT(*) count FROM employees e JOIN users u ON u.id=e.user_id WHERE u.is_active=0'),totalDepartments:q('SELECT COUNT(*) count FROM departments')}}); }
module.exports={departments,department,createDepartment,updateDepartment,deleteDepartment,employees,employee,createEmployee,updateEmployee,status,resetPassword,managers,adminStats};
