const db=require('../config/database'); const AppError=require('../utils/AppError');
const {notifyEmployee}=require('../utils/notificationService');
const {createTaskActivity}=require('../utils/taskActivityService');
const {getDeadlineCounts}=require('../utils/deadlineService');
const priorities=['Low','Medium','High'],statuses=['To Do','In Progress','Completed'];
const profile=(userId)=>db.prepare('SELECT e.id,e.manager_id,u.role FROM employees e JOIN users u ON u.id=e.user_id WHERE e.user_id=?').get(userId);
const task=(id)=>db.prepare(`SELECT t.*,a.first_name||' '||a.last_name assigned_name,c.first_name||' '||c.last_name creator_name,d.name department_name FROM tasks t JOIN employees a ON a.id=t.assigned_to JOIN employees c ON c.id=t.created_by LEFT JOIN departments d ON d.id=a.department_id WHERE t.id=?`).get(id);
function canView(t,p){return p.role==='admin'||(p.role==='manager'&&(t.created_by===p.id||t.assigned_to&&db.prepare('SELECT id FROM employees WHERE id=? AND manager_id=?').get(t.assigned_to,p.id)))||(p.role==='employee'&&t.assigned_to===p.id)}
function list(req,res){const p=profile(req.user.id),w=[],v=[];if(p.role==='manager'){w.push('(t.created_by=? OR a.manager_id=?)');v.push(p.id,p.id)}else if(p.role==='employee'){w.push('t.assigned_to=?');v.push(p.id)}if(req.query.status){w.push('t.status=?');v.push(req.query.status)}if(req.query.priority){w.push('t.priority=?');v.push(req.query.priority)}if(req.query.label_id){w.push('EXISTS (SELECT 1 FROM task_labels filter_tl WHERE filter_tl.task_id=t.id AND filter_tl.label_id=?)');v.push(req.query.label_id)}if(req.query.search){w.push('(t.title LIKE ? OR t.description LIKE ?)');v.push(`%${req.query.search}%`,`%${req.query.search}%`)}const sql=`SELECT t.*,a.first_name||' '||a.last_name assigned_name,c.first_name||' '||c.last_name creator_name FROM tasks t JOIN employees a ON a.id=t.assigned_to JOIN employees c ON c.id=t.created_by ${w.length?'WHERE '+w.join(' AND '):''} ORDER BY t.due_date`;res.json({success:true,data:db.prepare(sql).all(...v)});}
function detail(req,res){const t=task(req.params.id);if(!t)throw new AppError('Task not found.',404);if(!canView(t,profile(req.user.id)))throw new AppError('You are not authorized to access this task.',403);res.json({success:true,data:t});}
function validate(b){if(!b.title?.trim()||!b.assigned_to||!b.due_date)throw new AppError('Title, assignee, and due date are required.',400);if(!priorities.includes(b.priority))throw new AppError('Invalid priority.',400);if(Number.isNaN(Date.parse(b.due_date)))throw new AppError('Invalid due date.',400);}
function inTeam(id,manager){return db.prepare('SELECT id FROM employees WHERE id=? AND manager_id=?').get(id,manager);}
function create(req,res){const p=profile(req.user.id);validate(req.body);if(!inTeam(req.body.assigned_to,p.id))throw new AppError('Tasks can only be assigned to your team.',403);const b=req.body,r=db.prepare('INSERT INTO tasks(title,description,assigned_to,created_by,priority,due_date) VALUES(?,?,?,?,?,?)').run(b.title.trim(),b.description?.trim()||null,b.assigned_to,p.id,b.priority,b.due_date);const t=task(r.lastInsertRowid);createTaskActivity({taskId:t.id,actorUserId:req.user.id,activityType:'TASK_CREATED',newValue:t.title});createTaskActivity({taskId:t.id,actorUserId:req.user.id,activityType:'TASK_ASSIGNED',newValue:String(t.assigned_to)});const creator=db.prepare("SELECT first_name || ' ' || last_name AS full_name FROM employees WHERE id=?").get(p.id);const creatorName=creator?.full_name || 'Manager';const taskTitle=`Task assigned by ${creatorName}`;const taskMessage=`You have been assigned a new task by ${creatorName}: ${t.title}`;try{notifyEmployee(t.assigned_to,'task',taskTitle,taskMessage,'task',t.id)}catch{};res.status(201).json({success:true,data:t});}
function edit(req,res){const p=profile(req.user.id),old=task(req.params.id);if(!old)throw new AppError('Task not found.',404);if(old.created_by!==p.id)throw new AppError('Only the task creator can edit this task.',403);validate(req.body);if(!inTeam(req.body.assigned_to,p.id))throw new AppError('Tasks can only be assigned to your team.',403);const b=req.body;const title=b.title.trim(),description=b.description?.trim()||null,changedAssignee=Number(old.assigned_to)!==Number(b.assigned_to),changes=[];if(old.priority!==b.priority)changes.push({type:'PRIORITY_CHANGED',oldValue:old.priority,newValue:b.priority,message:`priority changed to ${b.priority}`});if(old.due_date!==b.due_date)changes.push({type:'DUE_DATE_CHANGED',oldValue:old.due_date,newValue:b.due_date,message:`due date changed to ${b.due_date}`});if((old.description||'')!==(description||''))changes.push({type:'DETAILS_UPDATED',oldValue:old.description||'',newValue:description||'',message:'description updated'});if(old.title!==title)changes.push({type:'DETAILS_UPDATED',oldValue:'title',newValue:title,message:'title updated'});db.prepare('UPDATE tasks SET title=?,description=?,assigned_to=?,priority=?,due_date=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(title,description,b.assigned_to,b.priority,b.due_date,old.id);for(const change of changes)createTaskActivity({taskId:old.id,actorUserId:req.user.id,activityType:change.type,oldValue:change.oldValue,newValue:change.newValue});if(changedAssignee){createTaskActivity({taskId:old.id,actorUserId:req.user.id,activityType:'TASK_REASSIGNED',oldValue:String(old.assigned_to),newValue:String(b.assigned_to)});try{notifyEmployee(old.assigned_to,'task','Task assignment changed',`The task "${old.title}" is no longer assigned to you.`,'task',old.id);notifyEmployee(b.assigned_to,'task','Task assigned to you',`You have been assigned the task "${old.title}".`,'task',old.id)}catch{}}if(changes.length){const message=`The task "${old.title}" was updated: ${changes.map(change=>change.message).join(', ')}.`;try{notifyEmployee(b.assigned_to,'task','Task details updated',message,'task',old.id);if(Number(b.assigned_to)!==Number(p.id))notifyEmployee(p.id,'task','Task details updated',message,'task',old.id)}catch{}}res.json({success:true,data:task(old.id)});}
function progress(req,res){const p=profile(req.user.id),t=task(req.params.id),b=req.body||{};if(!t)throw new AppError('Task not found.',404);if(t.assigned_to!==p.id)throw new AppError('You can only update your own tasks.',403);if(!statuses.includes(b.status)||!Number.isInteger(b.progress)||b.progress<0||b.progress>100)throw new AppError('Invalid status or progress.',400);const n=b.status==='Completed'?100:b.progress;if(b.status==='To Do'&&n!==0)throw new AppError('To Do tasks must have 0% progress.',400);if(b.status==='In Progress'&&(n<1||n>99))throw new AppError('In Progress tasks must be between 1% and 99%.',400);db.prepare('UPDATE tasks SET status=?,progress=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.status,n,t.id);if(t.status!==b.status)createTaskActivity({taskId:t.id,actorUserId:req.user.id,activityType:'STATUS_CHANGED',oldValue:t.status,newValue:b.status});if(t.progress!==n)createTaskActivity({taskId:t.id,actorUserId:req.user.id,activityType:'PROGRESS_CHANGED',oldValue:String(t.progress),newValue:String(n)});if(b.status==='Completed'&&t.status!=='Completed'){createTaskActivity({taskId:t.id,actorUserId:req.user.id,activityType:'TASK_COMPLETED'});try{notifyEmployee(t.created_by,'task','Task Completed',`The task "${t.title}" has been completed by the assigned employee.`,'task',t.id)}catch{}}res.json({success:true,data:task(t.id)});}
function remove(req,res){const p=profile(req.user.id),t=task(req.params.id);if(!t)throw new AppError('Task not found.',404);if(t.created_by!==p.id)throw new AppError('Only the task creator can delete this task.',403);db.prepare('DELETE FROM tasks WHERE id=?').run(t.id);res.json({success:true,message:'Task deleted.'});}
function team(req,res){const p=profile(req.user.id);res.json({success:true,data:db.prepare('SELECT e.id,e.first_name,e.last_name,e.employee_id,e.job_position FROM employees e JOIN users u ON u.id=e.user_id WHERE e.manager_id=? AND u.is_active=1 ORDER BY e.first_name').all(p.id)});}
function stats(req,res){const p=profile(req.user.id),base=p.role==='admin'?['','']:p.role==='manager'?[' WHERE (t.created_by=? OR a.manager_id=?)',[p.id,p.id]]:[' WHERE t.assigned_to=?',[p.id]];const count=(extra='')=>db.prepare(`SELECT COUNT(*) count FROM tasks t JOIN employees a ON a.id=t.assigned_to${base[0]}${extra}`).get(...base[1]).count;const join=base[0]?' AND ':' WHERE ';res.json({success:true,data:{total:count(),todo:count(join+"t.status='To Do'"),inProgress:count(join+"t.status='In Progress'"),completed:count(join+"t.status='Completed'"),overdue:count(join+"t.due_date < date('now') AND t.status != 'Completed'"),...getDeadlineCounts({role:p.role,employeeId:p.id})}});}
function employeeDashboard(req,res){const p=profile(req.user.id);if(!p||p.role!=='employee')throw new AppError('Employee access is required.',403);const count=(condition='')=>db.prepare(`SELECT COUNT(*) count FROM tasks WHERE assigned_to=?${condition}`).get(p.id).count;const recent=db.prepare(`SELECT id,title,priority,status,progress,due_date,created_at FROM tasks WHERE assigned_to=? ORDER BY updated_at DESC,created_at DESC LIMIT 5`).all(p.id);const deadlines=getDeadlineCounts({role:'employee',employeeId:p.id});res.json({success:true,data:{totalTasks:count(),todoTasks:count(" AND status='To Do'"),inProgressTasks:count(" AND status='In Progress'"),completedTasks:count(" AND status='Completed'"),overdueTasks:count(" AND due_date < date('now') AND status != 'Completed'"),dueToday:deadlines.dueToday,dueThisWeek:deadlines.dueThisWeek,recentTasks:recent}});}
module.exports={list,detail,create,edit,progress,remove,team,stats,employeeDashboard,canView,getTask:task,getProfile:profile};
