const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
require('./config/env');
require('./utils/taskSchema');
require('./utils/leaveSchema');
require('./utils/announcementSchema');
require('./utils/notificationSchema');
require('./utils/notificationPreferenceSchema');
require('./utils/employeeImportSchema');
require('./utils/onboardingSchema');
require('./utils/profileSchema');
require('./utils/taskActivitySchema');
require('./utils/taskCollaborationSchema');
require('./utils/taskFeaturesSchema');
const authRoutes = require('./routes/authRoutes');
const managementRoutes = require('./routes/managementRoutes');
const taskRoutes = require('./routes/taskRoutes');
const leaveRoutes = require('./routes/leaveRoutes');
const announcementRoutes = require('./routes/announcementRoutes');
const reportRoutes = require('./routes/reportRoutes');
const notificationRoutes = require('./routes/notificationRoutes');
const profileRoutes = require('./routes/profileRoutes');
const employeeImportRoutes = require('./routes/employeeImportRoutes');
const taskCollaborationRoutes = require('./routes/taskCollaborationRoutes');
const taskFeaturesRoutes = require('./routes/taskFeaturesRoutes');
const { notFound, errorHandler } = require('./middleware/errorMiddleware');

const { frontendOrigins } = require('./config/env');
const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: (origin, callback) => { if (!origin || frontendOrigins.includes(origin)) return callback(null, true); callback(new Error('Origin is not allowed.')); }, methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'], allowedHeaders: ['Content-Type', 'Authorization'], optionsSuccessStatus: 204 }));
app.use(express.json());
app.get('/api/health', (req, res) => res.json({ success: true, message: 'WorkSync API is running.' }));
app.use('/api/auth', authRoutes);
app.use('/api/profile', profileRoutes);
app.use('/api', employeeImportRoutes);
app.use('/api', notificationRoutes);
app.use('/api', taskCollaborationRoutes);
app.use('/api', taskFeaturesRoutes);
app.use('/api', taskRoutes);
app.use('/api', leaveRoutes);
app.use('/api', announcementRoutes);
app.use('/api', reportRoutes);
app.use('/api', managementRoutes);
app.use(notFound);
app.use(errorHandler);

module.exports = app;
