-- ============================================================================
-- WorkSync — PostgreSQL Schema Migration
-- ============================================================================
-- Reproduces the existing WorkSync SQLite schema (source of truth) in
-- PostgreSQL. The live SQLite database is located at:
--   %APPDATA%\WorkSync\database\worksync.sqlite
--
-- This script is intended for an EMPTY PostgreSQL database named `worksync`.
-- It is idempotent where practical (CREATE ... IF NOT EXISTS) and safe to run
-- against the target database more than once.
--
-- Type conversion notes (SQLite → PostgreSQL):
--   * INTEGER PRIMARY KEY AUTOINCREMENT → INTEGER GENERATED BY DEFAULT AS IDENTITY
--   * TEXT timestamps (SQLite CURRENT_TIMESTAMP / ISO-8601) → TIMESTAMP
--     (without time zone), with UTC defaults to match SQLite behavior
--   * TEXT date-only columns (due_date, joining_date, start_date, end_date) → DATE
--   * INTEGER boolean-style (0/1) columns → SMALLINT with CHECK (col IN (0,1))
--     so existing application 0/1 semantics and queries keep working
--   * COLLATE NOCASE on labels.name → unique index on LOWER(name)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. departments
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS departments (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT    NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at  TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

-- ----------------------------------------------------------------------------
-- 2. users
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                TEXT    NOT NULL UNIQUE,
    password             TEXT    NOT NULL,
    role                 TEXT    NOT NULL
                             CHECK (role IN ('admin', 'manager', 'employee')),
    is_active            SMALLINT NOT NULL DEFAULT 1
                             CHECK (is_active IN (0, 1)),
    created_at           TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at           TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    must_change_password SMALLINT NOT NULL DEFAULT 0
                             CHECK (must_change_password IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

-- ----------------------------------------------------------------------------
-- 3. employees
-- ----------------------------------------------------------------------------
-- Self-referencing FK (manager_id) plus FKs to users and departments.
-- `phone` was added to the live SQLite schema through a later migration, so it
-- is included here to reproduce the current live schema exactly.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS employees (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    employee_id     TEXT    NOT NULL UNIQUE,
    first_name      TEXT    NOT NULL,
    last_name       TEXT    NOT NULL,
    department_id   INTEGER REFERENCES departments (id) ON DELETE SET NULL,
    manager_id      INTEGER REFERENCES employees (id) ON DELETE SET NULL,
    job_position    TEXT    NOT NULL,
    joining_date    DATE    NOT NULL,
    profile_picture TEXT,
    phone           TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at      TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS idx_employees_department ON employees (department_id);
CREATE INDEX IF NOT EXISTS idx_employees_manager   ON employees (manager_id);

-- ----------------------------------------------------------------------------
-- 4. tasks
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT    NOT NULL,
    description TEXT,
    assigned_to INTEGER NOT NULL REFERENCES employees (id) ON DELETE RESTRICT,
    created_by  INTEGER NOT NULL REFERENCES employees (id) ON DELETE RESTRICT,
    priority    TEXT    NOT NULL
                      CHECK (priority IN ('Low', 'Medium', 'High'))
                      DEFAULT 'Medium',
    status      TEXT    NOT NULL
                      CHECK (status IN ('To Do', 'In Progress', 'Completed'))
                      DEFAULT 'To Do',
    progress    INTEGER NOT NULL DEFAULT 0
                      CHECK (progress BETWEEN 0 AND 100),
    due_date    DATE    NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at  TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks (assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_creator  ON tasks (created_by);
CREATE INDEX IF NOT EXISTS idx_tasks_status   ON tasks (status);

-- ----------------------------------------------------------------------------
-- 5. announcements
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS announcements (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           TEXT    NOT NULL,
    message         TEXT    NOT NULL,
    priority        TEXT    NOT NULL
                           CHECK (priority IN ('normal', 'important', 'urgent'))
                           DEFAULT 'normal',
    target_audience TEXT    NOT NULL
                           CHECK (target_audience IN ('all', 'managers', 'employees'))
                           DEFAULT 'all',
    created_by      INTEGER NOT NULL REFERENCES employees (id) ON DELETE RESTRICT,
    created_at      TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at      TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS idx_announcements_priority ON announcements (priority);
CREATE INDEX IF NOT EXISTS idx_announcements_audience ON announcements (target_audience);
CREATE INDEX IF NOT EXISTS idx_announcements_creator  ON announcements (created_by);

-- ----------------------------------------------------------------------------
-- 6. leave_requests
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leave_requests (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     INTEGER NOT NULL REFERENCES employees (id) ON DELETE RESTRICT,
    leave_type      TEXT    NOT NULL
                        CHECK (leave_type IN
                            ('Annual Leave', 'Sick Leave', 'Casual Leave',
                             'Unpaid Leave', 'Other')),
    start_date      DATE    NOT NULL,
    end_date        DATE    NOT NULL,
    reason          TEXT,
    status          TEXT    NOT NULL
                        CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Cancelled'))
                        DEFAULT 'Pending',
    reviewed_by     INTEGER REFERENCES employees (id) ON DELETE SET NULL,
    reviewed_at     TIMESTAMP,
    rejection_reason TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at      TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT chk_leave_start_before_end CHECK (start_date <= end_date)
);

CREATE INDEX IF NOT EXISTS idx_leave_employee ON leave_requests (employee_id);
CREATE INDEX IF NOT EXISTS idx_leave_status   ON leave_requests (status);
CREATE INDEX IF NOT EXISTS idx_leave_dates    ON leave_requests (start_date, end_date);

-- ----------------------------------------------------------------------------
-- 7. labels
-- ----------------------------------------------------------------------------
-- SQLite uses `name TEXT NOT NULL UNIQUE COLLATE NOCASE`.
-- PostgreSQL equivalent: a plain NOT NULL column plus a unique index over
-- LOWER(name) so that 'Bug' and 'bug' are treated as duplicates.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS labels (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT    NOT NULL,
    color      TEXT    NOT NULL DEFAULT 'indigo',
    created_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_labels_name_nocase ON labels (LOWER(name));

-- ----------------------------------------------------------------------------
-- 8. task_labels  (composite primary key)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_labels (
    task_id    INTEGER NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    label_id   INTEGER NOT NULL REFERENCES labels (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    PRIMARY KEY (task_id, label_id)
);

CREATE INDEX IF NOT EXISTS idx_task_labels_label ON task_labels (label_id);

-- ----------------------------------------------------------------------------
-- 9. task_subtasks
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_subtasks (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      INTEGER NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    title        TEXT    NOT NULL,
    is_completed SMALLINT NOT NULL DEFAULT 0
                        CHECK (is_completed IN (0, 1)),
    position     INTEGER NOT NULL DEFAULT 0,
    created_by   INTEGER NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    created_at   TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at   TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_task_subtasks_task_position
    ON task_subtasks (task_id, position, id);

-- ----------------------------------------------------------------------------
-- 10. task_comments
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_comments (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id        INTEGER NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    author_user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    body           TEXT    NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at     TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS idx_task_comments_task_time
    ON task_comments (task_id, created_at, id);

-- ----------------------------------------------------------------------------
-- 11. task_blockers
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_blockers (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             INTEGER NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    reported_by_user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    description         TEXT    NOT NULL,
    status              TEXT    NOT NULL
                               CHECK (status IN ('OPEN', 'RESOLVED'))
                               DEFAULT 'OPEN',
    resolved_by_user_id INTEGER REFERENCES users (id) ON DELETE SET NULL,
    resolved_at         TIMESTAMP,
    created_at          TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at          TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS idx_task_blockers_task_status
    ON task_blockers (task_id, status);

-- ----------------------------------------------------------------------------
-- 12. task_attachments
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_attachments (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id             INTEGER NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    uploaded_by_user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    original_name       TEXT    NOT NULL,
    stored_name         TEXT    NOT NULL UNIQUE,
    storage_path        TEXT    NOT NULL,
    mime_type           TEXT    NOT NULL,
    size_bytes          INTEGER NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS idx_task_attachments_task_time
    ON task_attachments (task_id, created_at, id);

-- ----------------------------------------------------------------------------
-- 13. task_activity
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_activity (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id        INTEGER NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    actor_user_id  INTEGER NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    activity_type  TEXT    NOT NULL,
    old_value      TEXT,
    new_value      TEXT,
    metadata       TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS idx_task_activity_task_time
    ON task_activity (task_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_task_activity_actor ON task_activity (actor_user_id);

-- ----------------------------------------------------------------------------
-- 14. notifications
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type                TEXT    NOT NULL
                                CHECK (type IN ('task', 'leave', 'announcement', 'system'))
                                DEFAULT 'system',
    title               TEXT    NOT NULL,
    message             TEXT    NOT NULL,
    related_entity_type TEXT,
    related_entity_id   INTEGER,
    is_read             SMALLINT NOT NULL DEFAULT 0
                                CHECK (is_read IN (0, 1)),
    created_at          TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at          TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE INDEX IF NOT EXISTS idx_notifications_user      ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications (user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_entity
    ON notifications (related_entity_type, related_entity_id);

-- ----------------------------------------------------------------------------
-- 15. notification_preferences  (composite primary key)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category   TEXT    NOT NULL,
    enabled    SMALLINT NOT NULL DEFAULT 1
                        CHECK (enabled IN (0, 1)),
    updated_at TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    PRIMARY KEY (user_id, category)
);

CREATE INDEX IF NOT EXISTS idx_notification_preferences_user
    ON notification_preferences (user_id);

-- ----------------------------------------------------------------------------
-- 16. employee_imports
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS employee_imports (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id     INTEGER NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    original_filename TEXT    NOT NULL,
    total_rows        INTEGER NOT NULL DEFAULT 0,
    imported_rows     INTEGER NOT NULL DEFAULT 0,
    failed_rows       INTEGER NOT NULL DEFAULT 0,
    duplicate_rows    INTEGER NOT NULL DEFAULT 0,
    status            TEXT    NOT NULL
                            CHECK (status IN ('completed', 'completed_with_errors', 'failed')),
    created_at        TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

-- SQLite declared this index with DESC on created_at; kept identical.
CREATE INDEX IF NOT EXISTS idx_employee_imports_admin_time
    ON employee_imports (admin_user_id, created_at DESC);