<template>
  <q-page class="q-pa-lg">
    <div class="row items-center q-mb-lg"><div><div class="text-overline text-primary">PLANNING</div><div class="page-title">Calendar</div><div class="muted">Review task deadlines and authorized leave dates in one view.</div></div><q-space /><q-btn flat icon="refresh" label="Refresh" :loading="loading" @click="load" /></div>
    <q-card flat bordered class="q-pa-lg"><div class="row q-col-gutter-md q-mb-lg"><q-select v-model="filters.status" outlined dense clearable label="Task status" :options="statuses" class="col-12 col-sm-3" /><q-select v-model="filters.priority" outlined dense clearable label="Priority" :options="priorities" class="col-12 col-sm-3" /><q-select v-model="filters.label_id" outlined dense clearable label="Label" :options="labels" option-value="id" option-label="name" emit-value map-options class="col-12 col-sm-3" /><q-btn flat icon="clear_all" label="Clear filters" @click="clearFilters" /></div><div class="row items-center"><q-btn flat round icon="chevron_left" @click="shiftMonth(-1)" /><div class="text-h6 text-weight-bold q-mx-md">{{ monthLabel }}</div><q-btn flat round icon="chevron_right" @click="shiftMonth(1)" /><q-space /><q-badge color="primary" :label="`${events.length} items`" /></div><div v-if="!loading && !events.length" class="text-center q-pa-xl muted"><q-icon name="event_busy" size="44px" color="indigo-3" /><div class="q-mt-sm">No task or leave dates match the current filters.</div></div><div class="calendar-grid q-mt-lg"><div v-for="day in days" :key="day.key" class="calendar-day" :class="{ 'calendar-today': day.isToday }"><div class="text-caption text-weight-bold">{{ day.label }}</div><q-item v-for="event in day.events" :key="event.key" dense clickable @click="openEvent(event)"><q-item-section avatar><q-icon :name="event.type === 'task' ? 'assignment' : 'event'" :color="event.type === 'task' ? 'primary' : 'positive'" /></q-item-section><q-item-section><q-item-label class="ellipsis">{{ event.title }}</q-item-label><q-item-label caption>{{ event.meta }}</q-item-label></q-item-section></q-item></div></div></q-card>
  </q-page>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useQuasar } from 'quasar'
import api from '../services/api'
const router = useRouter(), $q = useQuasar(), loading = ref(false), cursor = ref(new Date()), tasks = ref([]), leaves = ref([]), labels = ref([]), filters = ref({ status: null, priority: null, label_id: null }), statuses = ['To Do', 'In Progress', 'Completed'], priorities = ['Low', 'Medium', 'High']
const monthLabel = computed(() => cursor.value.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }))
const dateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const events = computed(() => [...tasks.value.filter((task) => task.due_date).map((task) => ({ key: `task-${task.id}`, date: task.due_date, type: 'task', title: task.title, meta: `${task.status} · ${task.priority}`, id: task.id })), ...leaves.value.flatMap((leave) => { const result = []; const start = new Date(`${leave.start_date}T00:00:00`); const end = new Date(`${leave.end_date}T00:00:00`); for (const date = new Date(start); date <= end; date.setDate(date.getDate() + 1)) result.push({ key: `leave-${leave.id}-${dateKey(date)}`, date: dateKey(date), type: 'leave', title: leave.employee_name || 'Leave request', meta: `${leave.leave_type} · ${leave.status}`, id: leave.id }); return result })])
const days = computed(() => { const first = new Date(cursor.value.getFullYear(), cursor.value.getMonth(), 1); const count = new Date(cursor.value.getFullYear(), cursor.value.getMonth() + 1, 0).getDate(); return Array.from({ length: count }, (_, index) => { const date = new Date(first); date.setDate(index + 1); const key = dateKey(date); return { key, label: `${date.getDate()} ${date.toLocaleDateString(undefined, { weekday: 'short' })}`, isToday: key === dateKey(new Date()), events: events.value.filter((event) => event.date === key) } }) })
async function load() { loading.value = true; try { const [taskResponse, leaveResponse, labelResponse] = await Promise.all([api.get('/tasks', { params: { status: filters.value.status, priority: filters.value.priority, label_id: filters.value.label_id } }), api.get('/leaves'), api.get('/labels')]); tasks.value = taskResponse.data.data; leaves.value = leaveResponse.data.data; labels.value = labelResponse.data.data } catch (error) { $q.notify({ type: 'negative', message: error.response?.data?.message || 'Unable to load calendar data.' }) } finally { loading.value = false } }
function clearFilters() { filters.value = { status: null, priority: null, label_id: null }; load() }
function shiftMonth(amount) { const next = new Date(cursor.value); next.setMonth(next.getMonth() + amount); cursor.value = next }
function openEvent(event) { if (event.type === 'task') router.push(`/tasks/${event.id}`); else router.push(`/leaves/${event.id}`) }
onMounted(load)
</script>
