<template>
  <q-page class="q-pa-lg">
    <div class="row items-center q-mb-lg"><div><div class="text-overline text-primary">ADMINISTRATION</div><div class="page-title">Employee import</div><div class="muted">Validate a CSV before importing employee accounts into WorkSync.</div></div><q-space /><q-btn flat icon="arrow_back" label="Back to employees" @click="router.push('/admin/employees')" /></div>
    <q-card flat bordered class="q-pa-lg">
      <div class="row items-center"><div><div class="text-h6">Upload employee CSV</div><div class="muted">Use the required columns below. Imports are all-or-nothing.</div></div><q-space /><q-btn flat icon="download" label="Download template" @click="downloadTemplate" /><q-btn flat color="negative" icon="delete_sweep" label="Reset demo data" @click="resetData" /></div>
      <div class="text-caption muted q-mt-md">Required: employee_id, first_name, last_name, email, department, role, manager_email, job_title, status. Optional: phone, team.</div>
      <q-file v-model="file" class="q-mt-lg" outlined accept=".csv,text/csv" max-file-size="2097152" label="Choose CSV file" @rejected="fileError = 'Only CSV files up to 2 MB are supported.'" />
      <div v-if="fileError" class="text-negative q-mt-sm">{{ fileError }}</div>
      <div class="row q-gutter-sm q-mt-md"><q-btn color="primary" unelevated label="Validate file" :disable="!file" :loading="loading" @click="preview" /><q-btn v-if="previewData" flat label="Clear" @click="clear" /></div>
    </q-card>
    <q-card v-if="previewData" flat bordered class="q-mt-lg q-pa-lg"><div class="row q-col-gutter-md"><div v-for="item in summaryItems" :key="item.label" class="col-6 col-sm-3"><div class="text-caption muted">{{ item.label }}</div><div class="text-h5 text-weight-bold q-mt-xs">{{ item.value }}</div></div></div><q-banner v-if="previewData.fileError" class="bg-red-1 text-negative q-mt-lg">{{ previewData.fileError }}</q-banner><q-table v-else class="q-mt-lg" flat bordered :rows="previewData.rows" :columns="columns" row-key="rowNumber" :pagination="{ rowsPerPage: 10 }"><template #body-cell-status="props"><q-td :props="props"><q-badge :color="props.row.status === 'Valid' ? 'positive' : props.row.status === 'Warning' ? 'warning' : 'negative'" :label="props.row.status" /><div v-if="props.row.errors.length" class="text-negative text-caption">{{ props.row.errors.join(' ') }}</div><div v-if="props.row.warnings.length" class="text-warning text-caption">{{ props.row.warnings.join(' ') }}</div></q-td></template></q-table><div class="row justify-end q-mt-lg"><q-btn color="primary" unelevated label="Import valid rows" :disable="previewData.summary.invalidRows > 0 || !previewData.summary.validRows" :loading="committing" @click="commit" /></div></q-card>
    <q-card v-if="credentials.length" flat bordered class="q-mt-lg q-pa-lg"><div class="text-h6">Temporary credentials</div><q-banner class="bg-orange-1 text-warning q-mt-md">Temporary passwords are shown only once. Save or distribute them securely before leaving this page.</q-banner><div class="row q-gutter-sm q-mt-md"><q-btn flat icon="content_copy" label="Copy all credentials" @click="copyAll" /><q-btn flat icon="download" label="Download credentials" @click="downloadCredentials" /></div><q-list separator class="q-mt-md"><q-item v-for="credential in credentials" :key="credential.email"><q-item-section><q-item-label>{{ credential.firstName }} {{ credential.lastName }} · {{ credential.employeeId }}</q-item-label><q-item-label caption>{{ credential.email }} · Temporary password: {{ credential.temporaryPassword }}</q-item-label></q-item-section><q-item-section side><q-btn flat round dense icon="content_copy" aria-label="Copy credentials" @click="copyCredential(credential)" /></q-item-section></q-item></q-list></q-card>
    <q-card flat bordered class="q-mt-lg q-pa-lg"><div class="text-h6">Import history</div><div class="muted">Recent employee import activity for administrators.</div><q-list v-if="history.length" separator class="q-mt-md"><q-item v-for="item in history" :key="item.id"><q-item-section><q-item-label>{{ item.original_filename }}</q-item-label><q-item-label caption>{{ item.created_at }} · {{ item.imported_rows }}/{{ item.total_rows }} imported</q-item-label></q-item-section><q-item-section side><q-badge :color="item.status === 'completed' ? 'positive' : item.status === 'completed_with_errors' ? 'warning' : 'negative'" :label="item.status" /></q-item-section></q-item></q-list><div v-else class="muted q-mt-md">No imports have been recorded.</div></q-card>
  </q-page>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { Notify } from 'quasar'
import { useRouter } from 'vue-router'
import api from '../services/api'
const router = useRouter(), file = ref(null), loading = ref(false), committing = ref(false), fileError = ref(''), previewData = ref(null), credentials = ref([]), history = ref([])
const columns = [{ name: 'rowNumber', label: 'Row', field: 'rowNumber' }, { name: 'employee_id', label: 'Employee ID', field: row => row.data.employee_id }, { name: 'email', label: 'Email', field: row => row.data.email }, { name: 'name', label: 'Name', field: row => `${row.data.first_name} ${row.data.last_name}` }, { name: 'status', label: 'Validation', field: 'status' }]
const summaryItems = computed(() => [{ label: 'Total rows', value: previewData.value?.summary.totalRows || 0 }, { label: 'Valid rows', value: previewData.value?.summary.validRows || 0 }, { label: 'Invalid rows', value: previewData.value?.summary.invalidRows || 0 }, { label: 'Warnings', value: previewData.value?.summary.warnings || 0 }])
function formData() { const data = new FormData(); data.append('file', file.value); return data }
async function preview() { loading.value = true; fileError.value = ''; try { previewData.value = (await api.post('/employee-imports/preview', formData())).data.data } catch (error) { fileError.value = error.response?.data?.message || 'Unable to validate the CSV.' } finally { loading.value = false } }
async function commit() { committing.value = true; try { const response = await api.post('/employee-imports/commit', formData()); credentials.value = response.data.data.imported || []; Notify.create({ type: 'positive', message: `${credentials.value.length} employees imported successfully.` }); previewData.value = null; file.value = null } catch (error) { const data = error.response?.data?.data; if (data) previewData.value = data; Notify.create({ type: 'negative', message: error.response?.data?.message || 'Import failed. No employees were imported.' }) } finally { committing.value = false } }
function clear() { file.value = null; previewData.value = null; credentials.value = []; fileError.value = '' }
function downloadTemplate() { const content = 'employee_id,first_name,last_name,email,phone,department,team,role,manager_email,job_title,status\nEMP001,Ali,Khan,ali.khan@company.com,03001234567,Engineering,Frontend Team,employee,manager.engineering@company.com,Software Engineer,active\n'; const blob = new Blob([content], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'worksync-employee-template.csv'; link.click(); URL.revokeObjectURL(link.href) }
async function resetData() { if (!confirm('This will remove existing demo employees and related development data. The database structure will not be deleted. Continue?')) return; try { await api.post('/employee-imports/reset', { confirmation: 'RESET_DEMO_DATA' }); clear(); history.value = []; Notify.create({ type: 'positive', message: 'Development data reset completed.' }) } catch (error) { Notify.create({ type: 'negative', message: error.response?.data?.message || 'Unable to reset development data.' }) } }
function credentialText(item) { return `${item.firstName} ${item.lastName},${item.employeeId},${item.email},${item.temporaryPassword}` }
async function copyCredential(item) { await navigator.clipboard.writeText(credentialText(item)); Notify.create({ type: 'positive', message: 'Credentials copied.' }) }
async function copyAll() { await navigator.clipboard.writeText(['Full name,Employee ID,Email,Temporary password', ...credentials.value.map(credentialText)].join('\n')); Notify.create({ type: 'positive', message: 'Credentials copied.' }) }
function downloadCredentials() { const content = ['Full name,Employee ID,Email,Temporary password', ...credentials.value.map(credentialText)].join('\n'); const blob = new Blob([content], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'worksync-temporary-credentials.csv'; link.click(); URL.revokeObjectURL(link.href) }
onMounted(async () => { try { history.value = (await api.get('/employee-imports')).data.data } catch {} })
</script>
